// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: calc.proto

#ifndef PROTOBUF_calc_2eproto__INCLUDED
#define PROTOBUF_calc_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pbrpc {
namespace examples {
namespace calc {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_calc_2eproto();
void protobuf_AssignDesc_calc_2eproto();
void protobuf_ShutdownFile_calc_2eproto();

class CalcRequest;
class CalcResponse;

// ===================================================================

class CalcRequest : public ::google::protobuf::Message {
 public:
  CalcRequest();
  virtual ~CalcRequest();

  CalcRequest(const CalcRequest& from);

  inline CalcRequest& operator=(const CalcRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CalcRequest& default_instance();

  void Swap(CalcRequest* other);

  // implements Message ----------------------------------------------

  CalcRequest* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CalcRequest& from);
  void MergeFrom(const CalcRequest& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated int32 nums = 1;
  inline int nums_size() const;
  inline void clear_nums();
  static const int kNumsFieldNumber = 1;
  inline ::google::protobuf::int32 nums(int index) const;
  inline void set_nums(int index, ::google::protobuf::int32 value);
  inline void add_nums(::google::protobuf::int32 value);
  inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
      nums() const;
  inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
      mutable_nums();

  // @@protoc_insertion_point(class_scope:pbrpc.examples.calc.CalcRequest)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::RepeatedField< ::google::protobuf::int32 > nums_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_calc_2eproto();
  friend void protobuf_AssignDesc_calc_2eproto();
  friend void protobuf_ShutdownFile_calc_2eproto();

  void InitAsDefaultInstance();
  static CalcRequest* default_instance_;
};
// -------------------------------------------------------------------

class CalcResponse : public ::google::protobuf::Message {
 public:
  CalcResponse();
  virtual ~CalcResponse();

  CalcResponse(const CalcResponse& from);

  inline CalcResponse& operator=(const CalcResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const CalcResponse& default_instance();

  void Swap(CalcResponse* other);

  // implements Message ----------------------------------------------

  CalcResponse* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CalcResponse& from);
  void MergeFrom(const CalcResponse& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 result = 1;
  inline bool has_result() const;
  inline void clear_result();
  static const int kResultFieldNumber = 1;
  inline ::google::protobuf::int32 result() const;
  inline void set_result(::google::protobuf::int32 value);

  // @@protoc_insertion_point(class_scope:pbrpc.examples.calc.CalcResponse)
 private:
  inline void set_has_result();
  inline void clear_has_result();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 result_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];

  friend void  protobuf_AddDesc_calc_2eproto();
  friend void protobuf_AssignDesc_calc_2eproto();
  friend void protobuf_ShutdownFile_calc_2eproto();

  void InitAsDefaultInstance();
  static CalcResponse* default_instance_;
};
// ===================================================================

class CalcService_Stub;

class CalcService : public ::google::protobuf::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline CalcService() {};
 public:
  virtual ~CalcService();

  typedef CalcService_Stub Stub;

  static const ::google::protobuf::ServiceDescriptor* descriptor();

  virtual void Calc(::google::protobuf::RpcController* controller,
                       const ::pbrpc::examples::calc::CalcRequest* request,
                       ::pbrpc::examples::calc::CalcResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::google::protobuf::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::google::protobuf::MethodDescriptor* method,
                  ::google::protobuf::RpcController* controller,
                  const ::google::protobuf::Message* request,
                  ::google::protobuf::Message* response,
                  ::google::protobuf::Closure* done);
  const ::google::protobuf::Message& GetRequestPrototype(
    const ::google::protobuf::MethodDescriptor* method) const;
  const ::google::protobuf::Message& GetResponsePrototype(
    const ::google::protobuf::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(CalcService);
};

class CalcService_Stub : public CalcService {
 public:
  CalcService_Stub(::google::protobuf::RpcChannel* channel);
  CalcService_Stub(::google::protobuf::RpcChannel* channel,
                   ::google::protobuf::Service::ChannelOwnership ownership);
  ~CalcService_Stub();

  inline ::google::protobuf::RpcChannel* channel() { return channel_; }

  // implements CalcService ------------------------------------------

  void Calc(::google::protobuf::RpcController* controller,
                       const ::pbrpc::examples::calc::CalcRequest* request,
                       ::pbrpc::examples::calc::CalcResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::google::protobuf::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(CalcService_Stub);
};


// ===================================================================


// ===================================================================

// CalcRequest

// repeated int32 nums = 1;
inline int CalcRequest::nums_size() const {
  return nums_.size();
}
inline void CalcRequest::clear_nums() {
  nums_.Clear();
}
inline ::google::protobuf::int32 CalcRequest::nums(int index) const {
  return nums_.Get(index);
}
inline void CalcRequest::set_nums(int index, ::google::protobuf::int32 value) {
  nums_.Set(index, value);
}
inline void CalcRequest::add_nums(::google::protobuf::int32 value) {
  nums_.Add(value);
}
inline const ::google::protobuf::RepeatedField< ::google::protobuf::int32 >&
CalcRequest::nums() const {
  return nums_;
}
inline ::google::protobuf::RepeatedField< ::google::protobuf::int32 >*
CalcRequest::mutable_nums() {
  return &nums_;
}

// -------------------------------------------------------------------

// CalcResponse

// required int32 result = 1;
inline bool CalcResponse::has_result() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CalcResponse::set_has_result() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CalcResponse::clear_has_result() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CalcResponse::clear_result() {
  result_ = 0;
  clear_has_result();
}
inline ::google::protobuf::int32 CalcResponse::result() const {
  return result_;
}
inline void CalcResponse::set_result(::google::protobuf::int32 value) {
  set_has_result();
  result_ = value;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace calc
}  // namespace examples
}  // namespace pbrpc

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_calc_2eproto__INCLUDED
