// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#ifndef PROTOBUF_message_2eproto__INCLUDED
#define PROTOBUF_message_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace pbrpc {
namespace proto {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_message_2eproto();
void protobuf_AssignDesc_message_2eproto();
void protobuf_ShutdownFile_message_2eproto();

class RequestMsg;
class ResponseMsg;

enum RequestMsgType {
  NORMAL = 0,
  CANCEL = 1
};
bool RequestMsgType_IsValid(int value);
const RequestMsgType RequestMsgType_MIN = NORMAL;
const RequestMsgType RequestMsgType_MAX = CANCEL;
const int RequestMsgType_ARRAYSIZE = RequestMsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* RequestMsgType_descriptor();
inline const ::std::string& RequestMsgType_Name(RequestMsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    RequestMsgType_descriptor(), value);
}
inline bool RequestMsgType_Parse(
    const ::std::string& name, RequestMsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<RequestMsgType>(
    RequestMsgType_descriptor(), name, value);
}
enum ResponseMsgType {
  SUCCESS = 0,
  FAIL = 1
};
bool ResponseMsgType_IsValid(int value);
const ResponseMsgType ResponseMsgType_MIN = SUCCESS;
const ResponseMsgType ResponseMsgType_MAX = FAIL;
const int ResponseMsgType_ARRAYSIZE = ResponseMsgType_MAX + 1;

const ::google::protobuf::EnumDescriptor* ResponseMsgType_descriptor();
inline const ::std::string& ResponseMsgType_Name(ResponseMsgType value) {
  return ::google::protobuf::internal::NameOfEnum(
    ResponseMsgType_descriptor(), value);
}
inline bool ResponseMsgType_Parse(
    const ::std::string& name, ResponseMsgType* value) {
  return ::google::protobuf::internal::ParseNamedEnum<ResponseMsgType>(
    ResponseMsgType_descriptor(), name, value);
}
// ===================================================================

class RequestMsg : public ::google::protobuf::Message {
 public:
  RequestMsg();
  virtual ~RequestMsg();

  RequestMsg(const RequestMsg& from);

  inline RequestMsg& operator=(const RequestMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const RequestMsg& default_instance();

  void Swap(RequestMsg* other);

  // implements Message ----------------------------------------------

  RequestMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RequestMsg& from);
  void MergeFrom(const RequestMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required .pbrpc.proto.RequestMsgType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::pbrpc::proto::RequestMsgType type() const;
  inline void set_type(::pbrpc::proto::RequestMsgType value);

  // optional string service_name = 10;
  inline bool has_service_name() const;
  inline void clear_service_name();
  static const int kServiceNameFieldNumber = 10;
  inline const ::std::string& service_name() const;
  inline void set_service_name(const ::std::string& value);
  inline void set_service_name(const char* value);
  inline void set_service_name(const char* value, size_t size);
  inline ::std::string* mutable_service_name();
  inline ::std::string* release_service_name();
  inline void set_allocated_service_name(::std::string* service_name);

  // optional string method_name = 11;
  inline bool has_method_name() const;
  inline void clear_method_name();
  static const int kMethodNameFieldNumber = 11;
  inline const ::std::string& method_name() const;
  inline void set_method_name(const ::std::string& value);
  inline void set_method_name(const char* value);
  inline void set_method_name(const char* value, size_t size);
  inline ::std::string* mutable_method_name();
  inline ::std::string* release_method_name();
  inline void set_allocated_method_name(::std::string* method_name);

  // optional bytes request_body = 12;
  inline bool has_request_body() const;
  inline void clear_request_body();
  static const int kRequestBodyFieldNumber = 12;
  inline const ::std::string& request_body() const;
  inline void set_request_body(const ::std::string& value);
  inline void set_request_body(const char* value);
  inline void set_request_body(const void* value, size_t size);
  inline ::std::string* mutable_request_body();
  inline ::std::string* release_request_body();
  inline void set_allocated_request_body(::std::string* request_body);

  // @@protoc_insertion_point(class_scope:pbrpc.proto.RequestMsg)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_service_name();
  inline void clear_has_service_name();
  inline void set_has_method_name();
  inline void clear_has_method_name();
  inline void set_has_request_body();
  inline void clear_has_request_body();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  int type_;
  ::std::string* service_name_;
  ::std::string* method_name_;
  ::std::string* request_body_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static RequestMsg* default_instance_;
};
// -------------------------------------------------------------------

class ResponseMsg : public ::google::protobuf::Message {
 public:
  ResponseMsg();
  virtual ~ResponseMsg();

  ResponseMsg(const ResponseMsg& from);

  inline ResponseMsg& operator=(const ResponseMsg& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const ResponseMsg& default_instance();

  void Swap(ResponseMsg* other);

  // implements Message ----------------------------------------------

  ResponseMsg* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const ResponseMsg& from);
  void MergeFrom(const ResponseMsg& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // required int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);

  // required .pbrpc.proto.ResponseMsgType type = 2;
  inline bool has_type() const;
  inline void clear_type();
  static const int kTypeFieldNumber = 2;
  inline ::pbrpc::proto::ResponseMsgType type() const;
  inline void set_type(::pbrpc::proto::ResponseMsgType value);

  // optional bytes response_body = 10;
  inline bool has_response_body() const;
  inline void clear_response_body();
  static const int kResponseBodyFieldNumber = 10;
  inline const ::std::string& response_body() const;
  inline void set_response_body(const ::std::string& value);
  inline void set_response_body(const char* value);
  inline void set_response_body(const void* value, size_t size);
  inline ::std::string* mutable_response_body();
  inline ::std::string* release_response_body();
  inline void set_allocated_response_body(::std::string* response_body);

  // optional string error_text = 11;
  inline bool has_error_text() const;
  inline void clear_error_text();
  static const int kErrorTextFieldNumber = 11;
  inline const ::std::string& error_text() const;
  inline void set_error_text(const ::std::string& value);
  inline void set_error_text(const char* value);
  inline void set_error_text(const char* value, size_t size);
  inline ::std::string* mutable_error_text();
  inline ::std::string* release_error_text();
  inline void set_allocated_error_text(::std::string* error_text);

  // @@protoc_insertion_point(class_scope:pbrpc.proto.ResponseMsg)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_type();
  inline void clear_has_type();
  inline void set_has_response_body();
  inline void clear_has_response_body();
  inline void set_has_error_text();
  inline void clear_has_error_text();

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::int32 id_;
  int type_;
  ::std::string* response_body_;
  ::std::string* error_text_;

  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];

  friend void  protobuf_AddDesc_message_2eproto();
  friend void protobuf_AssignDesc_message_2eproto();
  friend void protobuf_ShutdownFile_message_2eproto();

  void InitAsDefaultInstance();
  static ResponseMsg* default_instance_;
};
// ===================================================================


// ===================================================================

// RequestMsg

// required int32 id = 1;
inline bool RequestMsg::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RequestMsg::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RequestMsg::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RequestMsg::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 RequestMsg::id() const {
  return id_;
}
inline void RequestMsg::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required .pbrpc.proto.RequestMsgType type = 2;
inline bool RequestMsg::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RequestMsg::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RequestMsg::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RequestMsg::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::pbrpc::proto::RequestMsgType RequestMsg::type() const {
  return static_cast< ::pbrpc::proto::RequestMsgType >(type_);
}
inline void RequestMsg::set_type(::pbrpc::proto::RequestMsgType value) {
  assert(::pbrpc::proto::RequestMsgType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional string service_name = 10;
inline bool RequestMsg::has_service_name() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void RequestMsg::set_has_service_name() {
  _has_bits_[0] |= 0x00000004u;
}
inline void RequestMsg::clear_has_service_name() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void RequestMsg::clear_service_name() {
  if (service_name_ != &::google::protobuf::internal::kEmptyString) {
    service_name_->clear();
  }
  clear_has_service_name();
}
inline const ::std::string& RequestMsg::service_name() const {
  return *service_name_;
}
inline void RequestMsg::set_service_name(const ::std::string& value) {
  set_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    service_name_ = new ::std::string;
  }
  service_name_->assign(value);
}
inline void RequestMsg::set_service_name(const char* value) {
  set_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    service_name_ = new ::std::string;
  }
  service_name_->assign(value);
}
inline void RequestMsg::set_service_name(const char* value, size_t size) {
  set_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    service_name_ = new ::std::string;
  }
  service_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RequestMsg::mutable_service_name() {
  set_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    service_name_ = new ::std::string;
  }
  return service_name_;
}
inline ::std::string* RequestMsg::release_service_name() {
  clear_has_service_name();
  if (service_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = service_name_;
    service_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RequestMsg::set_allocated_service_name(::std::string* service_name) {
  if (service_name_ != &::google::protobuf::internal::kEmptyString) {
    delete service_name_;
  }
  if (service_name) {
    set_has_service_name();
    service_name_ = service_name;
  } else {
    clear_has_service_name();
    service_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string method_name = 11;
inline bool RequestMsg::has_method_name() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void RequestMsg::set_has_method_name() {
  _has_bits_[0] |= 0x00000008u;
}
inline void RequestMsg::clear_has_method_name() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void RequestMsg::clear_method_name() {
  if (method_name_ != &::google::protobuf::internal::kEmptyString) {
    method_name_->clear();
  }
  clear_has_method_name();
}
inline const ::std::string& RequestMsg::method_name() const {
  return *method_name_;
}
inline void RequestMsg::set_method_name(const ::std::string& value) {
  set_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    method_name_ = new ::std::string;
  }
  method_name_->assign(value);
}
inline void RequestMsg::set_method_name(const char* value) {
  set_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    method_name_ = new ::std::string;
  }
  method_name_->assign(value);
}
inline void RequestMsg::set_method_name(const char* value, size_t size) {
  set_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    method_name_ = new ::std::string;
  }
  method_name_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RequestMsg::mutable_method_name() {
  set_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    method_name_ = new ::std::string;
  }
  return method_name_;
}
inline ::std::string* RequestMsg::release_method_name() {
  clear_has_method_name();
  if (method_name_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = method_name_;
    method_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RequestMsg::set_allocated_method_name(::std::string* method_name) {
  if (method_name_ != &::google::protobuf::internal::kEmptyString) {
    delete method_name_;
  }
  if (method_name) {
    set_has_method_name();
    method_name_ = method_name;
  } else {
    clear_has_method_name();
    method_name_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional bytes request_body = 12;
inline bool RequestMsg::has_request_body() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void RequestMsg::set_has_request_body() {
  _has_bits_[0] |= 0x00000010u;
}
inline void RequestMsg::clear_has_request_body() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void RequestMsg::clear_request_body() {
  if (request_body_ != &::google::protobuf::internal::kEmptyString) {
    request_body_->clear();
  }
  clear_has_request_body();
}
inline const ::std::string& RequestMsg::request_body() const {
  return *request_body_;
}
inline void RequestMsg::set_request_body(const ::std::string& value) {
  set_has_request_body();
  if (request_body_ == &::google::protobuf::internal::kEmptyString) {
    request_body_ = new ::std::string;
  }
  request_body_->assign(value);
}
inline void RequestMsg::set_request_body(const char* value) {
  set_has_request_body();
  if (request_body_ == &::google::protobuf::internal::kEmptyString) {
    request_body_ = new ::std::string;
  }
  request_body_->assign(value);
}
inline void RequestMsg::set_request_body(const void* value, size_t size) {
  set_has_request_body();
  if (request_body_ == &::google::protobuf::internal::kEmptyString) {
    request_body_ = new ::std::string;
  }
  request_body_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* RequestMsg::mutable_request_body() {
  set_has_request_body();
  if (request_body_ == &::google::protobuf::internal::kEmptyString) {
    request_body_ = new ::std::string;
  }
  return request_body_;
}
inline ::std::string* RequestMsg::release_request_body() {
  clear_has_request_body();
  if (request_body_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = request_body_;
    request_body_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void RequestMsg::set_allocated_request_body(::std::string* request_body) {
  if (request_body_ != &::google::protobuf::internal::kEmptyString) {
    delete request_body_;
  }
  if (request_body) {
    set_has_request_body();
    request_body_ = request_body;
  } else {
    clear_has_request_body();
    request_body_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// -------------------------------------------------------------------

// ResponseMsg

// required int32 id = 1;
inline bool ResponseMsg::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void ResponseMsg::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void ResponseMsg::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void ResponseMsg::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 ResponseMsg::id() const {
  return id_;
}
inline void ResponseMsg::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// required .pbrpc.proto.ResponseMsgType type = 2;
inline bool ResponseMsg::has_type() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void ResponseMsg::set_has_type() {
  _has_bits_[0] |= 0x00000002u;
}
inline void ResponseMsg::clear_has_type() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void ResponseMsg::clear_type() {
  type_ = 0;
  clear_has_type();
}
inline ::pbrpc::proto::ResponseMsgType ResponseMsg::type() const {
  return static_cast< ::pbrpc::proto::ResponseMsgType >(type_);
}
inline void ResponseMsg::set_type(::pbrpc::proto::ResponseMsgType value) {
  assert(::pbrpc::proto::ResponseMsgType_IsValid(value));
  set_has_type();
  type_ = value;
}

// optional bytes response_body = 10;
inline bool ResponseMsg::has_response_body() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void ResponseMsg::set_has_response_body() {
  _has_bits_[0] |= 0x00000004u;
}
inline void ResponseMsg::clear_has_response_body() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void ResponseMsg::clear_response_body() {
  if (response_body_ != &::google::protobuf::internal::kEmptyString) {
    response_body_->clear();
  }
  clear_has_response_body();
}
inline const ::std::string& ResponseMsg::response_body() const {
  return *response_body_;
}
inline void ResponseMsg::set_response_body(const ::std::string& value) {
  set_has_response_body();
  if (response_body_ == &::google::protobuf::internal::kEmptyString) {
    response_body_ = new ::std::string;
  }
  response_body_->assign(value);
}
inline void ResponseMsg::set_response_body(const char* value) {
  set_has_response_body();
  if (response_body_ == &::google::protobuf::internal::kEmptyString) {
    response_body_ = new ::std::string;
  }
  response_body_->assign(value);
}
inline void ResponseMsg::set_response_body(const void* value, size_t size) {
  set_has_response_body();
  if (response_body_ == &::google::protobuf::internal::kEmptyString) {
    response_body_ = new ::std::string;
  }
  response_body_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ResponseMsg::mutable_response_body() {
  set_has_response_body();
  if (response_body_ == &::google::protobuf::internal::kEmptyString) {
    response_body_ = new ::std::string;
  }
  return response_body_;
}
inline ::std::string* ResponseMsg::release_response_body() {
  clear_has_response_body();
  if (response_body_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = response_body_;
    response_body_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ResponseMsg::set_allocated_response_body(::std::string* response_body) {
  if (response_body_ != &::google::protobuf::internal::kEmptyString) {
    delete response_body_;
  }
  if (response_body) {
    set_has_response_body();
    response_body_ = response_body;
  } else {
    clear_has_response_body();
    response_body_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}

// optional string error_text = 11;
inline bool ResponseMsg::has_error_text() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void ResponseMsg::set_has_error_text() {
  _has_bits_[0] |= 0x00000008u;
}
inline void ResponseMsg::clear_has_error_text() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void ResponseMsg::clear_error_text() {
  if (error_text_ != &::google::protobuf::internal::kEmptyString) {
    error_text_->clear();
  }
  clear_has_error_text();
}
inline const ::std::string& ResponseMsg::error_text() const {
  return *error_text_;
}
inline void ResponseMsg::set_error_text(const ::std::string& value) {
  set_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    error_text_ = new ::std::string;
  }
  error_text_->assign(value);
}
inline void ResponseMsg::set_error_text(const char* value) {
  set_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    error_text_ = new ::std::string;
  }
  error_text_->assign(value);
}
inline void ResponseMsg::set_error_text(const char* value, size_t size) {
  set_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    error_text_ = new ::std::string;
  }
  error_text_->assign(reinterpret_cast<const char*>(value), size);
}
inline ::std::string* ResponseMsg::mutable_error_text() {
  set_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    error_text_ = new ::std::string;
  }
  return error_text_;
}
inline ::std::string* ResponseMsg::release_error_text() {
  clear_has_error_text();
  if (error_text_ == &::google::protobuf::internal::kEmptyString) {
    return NULL;
  } else {
    ::std::string* temp = error_text_;
    error_text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
    return temp;
  }
}
inline void ResponseMsg::set_allocated_error_text(::std::string* error_text) {
  if (error_text_ != &::google::protobuf::internal::kEmptyString) {
    delete error_text_;
  }
  if (error_text) {
    set_has_error_text();
    error_text_ = error_text;
  } else {
    clear_has_error_text();
    error_text_ = const_cast< ::std::string*>(&::google::protobuf::internal::kEmptyString);
  }
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace proto
}  // namespace pbrpc

#ifndef SWIG
namespace google {
namespace protobuf {

template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pbrpc::proto::RequestMsgType>() {
  return ::pbrpc::proto::RequestMsgType_descriptor();
}
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::pbrpc::proto::ResponseMsgType>() {
  return ::pbrpc::proto::ResponseMsgType_descriptor();
}

}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_message_2eproto__INCLUDED
